export enum ErrorCode {
    INVALID_TOKEN = 1,
    INVALID_PAYLOAD = 2,
    INVALID_PASSWORD = 3,

    MISSING_TOKEN = 4,
    NOT_ALLOWED = 5,
    INTERNAL_ERROR = 6,
    USER_NOT_FOUND = 7,
    ACCOUNT_LOCKED = 8
}
